controlPlaneNumber: 3
workersNumber: 3
ingressNumber: 2

# GPU node configurations
gpuTypes:
  l4:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "l4"
  l40:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "l40"
  h100:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "h100"
  h200:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "h200"
  b200:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "b200"
  b200vm:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "b200vm"

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"
  serviceDomain: "cluster.local"

clusterLabels: {}

ccmRegional: true

identityRef:
  name: ""
  cloudName: ""
  region: ""

bastion:
  enabled: true
  spec:
    providerID: ""
    flavor: ""
    image:
      filter:
        name: ""
controlPlaneAvailabilityZones:
  - nova

managedSecurityGroups:
  allowAllInClusterTraffic: false

managedSubnets:
- cidr: 10.6.0.0/24

apiServerLoadBalancer:
  enabled: true

networkMTU: 1500

disableExternalNetwork: false

externalNetwork:
  filter:
    name: ""

controlPlane:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

worker:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

ingress:
  sshPublicKey: ""
  providerID: ""
  flavor: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

# GPU machine specifications - consolidated configuration
gpu:
  # Common configuration for all GPU types
  sshPublicKey: ""
  providerID: ""
  image:
    filter:
      name: ""
  ports: []
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""
  # GPU-specific configurations
  types:
    l4:
      flavor: ""
    l40:
      flavor: ""
    h100:
      flavor: ""
    h200:
      flavor: ""
    b200:
      flavor: ""
    b200vm:
      flavor: ""

k0s:
  version: v1.32.3+k0s.0
  api:
    extraArgs:
      anonymous-auth: "true"
      # OIDC configuration (optional - uncomment and configure as needed)
      # oidc-client-id: ""
      # oidc-groups-claim: "groups"
      # oidc-groups-prefix: ""
      # oidc-issuer-url: ""
      # oidc-username-claim: "name"
      # oidc-username-prefix: ""
  
  # Files to deploy to control plane nodes
  files:
    # GPU-aware scheduler configuration
    - path: /etc/k0s/scheduler-config.yaml
      permissions: "0644"
      content: |
        apiVersion: kubescheduler.config.k8s.io/v1
        kind: KubeSchedulerConfiguration
        clientConnection:
          kubeconfig: /var/lib/k0s/pki/scheduler.conf
        profiles:
        - schedulerName: default-scheduler
          plugins:
            score:
              enabled:
              - name: NodeResourcesFit
                weight: 100
              disabled:
              - name: NodeResourcesFit
          pluginConfig:
          - name: NodeResourcesFit
            args:
              scoringStrategy:
                type: MostAllocated
                resources:
                - name: nvidia.com/gpu
                  weight: 100
                - name: cpu
                  weight: 1
                - name: memory
                  weight: 1

