controlPlaneNumber: 3
workersNumber: 3
ingressNumber: 2

# GPU node configurations
gpuTypes:
  l4:
    replicas: 0  # Set to desired number when needed
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "l4"
  l40:
    replicas: 0  # Set to desired number when needed
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "l40"
  h100:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "h100"
  h200:
    replicas: 0  # Set to desired number when needed
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "h200"
  b200:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "b200"
  b200vm:
    replicas: 0
    nodeLabels:
      node-role.kubernetes.io/gpu: ""
      node.kubernetes.io/role: gpu
      node.kubernetes.io/gpu-type: "b200vm"

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"
  serviceDomain: "cluster.local"

clusterLabels: {}

ccmRegional: true

identityRef:
  name: "openstack-cloud-config"
  cloudName: "openstack"
  region: "RegionOne"

bastion:
  enabled: true
  spec:
    providerID: ""
    flavor: "m1.small"
    image:
      filter:
        name: "ubuntu-noble-server-amd64"

managedSecurityGroups:
  allowAllInClusterTraffic: true

managedSubnets:
- cidr: 10.6.0.0/24

apiServerLoadBalancer:
  enabled: true

networkMTU: 1500

externalNetwork:
  filter:
    name: "Public_Net_Vlan_3009"

controlPlane:
  sshPublicKey: "k0rdent-key"
  providerID: ""
  flavor: "inference-control-plane"
  image:
    filter:
      name: "gcore-ubuntu-noble-master-1-31-5"
  ports: []
  rootVolume:
    sizeGiB: 100
    type: "netapp-nvme"
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

worker:
  sshPublicKey: "k0rdent-key"
  providerID: ""
  flavor: "inference-worker-infra"
  image:
    filter:
      name: "gcore-ubuntu-noble-worker-1-31-5"
  ports: []
  rootVolume:
    sizeGiB: 100
    type: "netapp-nvme"
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

ingress:
  sshPublicKey: "k0rdent-key"
  providerID: ""
  flavor: "inference-ingress"
  image:
    filter:
      name: "gcore-ubuntu-noble-worker-1-31-5"
  ports: []
  rootVolume:
    sizeGiB: 100
    type: "netapp-nvme"
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""

# GPU machine specifications - consolidated configuration
gpu:
  # Common configuration for all GPU types
  sshPublicKey: "k0rdent-key"
  providerID: ""
  image:
    filter:
      name: "gcore-ubuntu-noble-worker-1-31-5-bm"
  ports:
  - network:
      filter:
        name: "Ironic_Vlan_1505"
  rootVolume: {}
  additionalBlockDevices: []
  securityGroups:
  - filter:
      name: "default"
      description: ""
      projectID: ""
  # GPU-specific configurations
  types:
    l4:
      flavor: "bm-server-l4"
    l40:
      flavor: "bm-server-l40"
    h100:
      flavor: ""
    h200:
      flavor: "baremetal-hgx"
    b200:
      flavor: ""
    b200vm:
      flavor: ""

k0s:
  version: v1.32.3+k0s.0
  api:
    extraArgs:
      anonymous-auth: "true"
      # OIDC configuration (optional - uncomment and configure as needed)
      # oidc-client-id: ""
      # oidc-groups-claim: "groups"
      # oidc-groups-prefix: ""
      # oidc-issuer-url: ""
      # oidc-username-claim: "name"
      # oidc-username-prefix: ""