{{- $gpuTypes := list "l4" "l40" "h100" "h200" "b200" "b200vm" }}
{{- range $gpuType := $gpuTypes }}
{{- $gpuConfig := index $.Values.gpuWorker $gpuType }}
{{- if and $gpuConfig (gt ($gpuConfig.number | int) 0) }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.gpu.name" (dict "root" $ "gpuType" $gpuType) }}
  annotations:
    # Temporary fix to address https://github.com/k0sproject/k0smotron/issues/911
    machineset.cluster.x-k8s.io/skip-preflight-checks: "ControlPlaneIsStable"
spec:
  clusterName: {{ include "cluster.name" $ }}
  replicas: {{ $gpuConfig.number }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" $ }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" $ }}
        node-role.kubernetes.io/gpu: ""
        node.kubernetes.io/role: gpu
        node.kubernetes.io/gpu-type: {{ $gpuType }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "cluster.name" $ }}-{{ $gpuType }}-machine-config
      clusterName: {{ include "cluster.name" $ }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: {{ include "openstackmachinetemplate.gpu.name" (dict "root" $ "gpuType" $gpuType) }}
{{- end }}
{{- end }}