apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: {{ include "openstackmachinetemplate.ingress.name" . }}
spec:
  template:
    spec:
      flavor: {{ .Values.ingress.flavor }}
      identityRef:
        name: {{ .Values.identityRef.name }}
        region: {{ .Values.identityRef.region }}
        cloudName: {{ .Values.identityRef.cloudName}}
      image:
        filter:
          name: {{ .Values.ingress.image.filter.name }}
          {{- if .Values.ingress.image.filter.tags }}
          tags:
            {{- range $tag := .Values.ingress.image.filter.tags }}
            - {{ $tag }}
            {{- end }}
          {{- end }}
      {{- if gt (len .Values.ingress.ports) 0 }}
      ports:
        {{ .Values.ingress.ports | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.ingress.rootVolume }}
      rootVolume:
        {{ .Values.ingress.rootVolume | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.ingress.additionalBlockDevices) 0 }}
      additionalBlockDevices:
        {{ .Values.ingress.additionalBlockDevices | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.ingress.securityGroups) 0 }}
      securityGroups:
        {{ .Values.ingress.securityGroups | toYaml | nindent 8 }}
      {{- end }}
      {{- if not ( .Values.ingress.sshPublicKey | empty) }}
      sshKeyName: {{ .Values.ingress.sshPublicKey }}
      {{- end }}
      {{- if not ( .Values.ingress.schedulerHintAdditionalProperties | empty) }}:
      schedulerHintAdditionalProperties:
        {{ .Values.ingress.schedulerHintAdditionalProperties | toYaml | nindent 8 }}
      {{- end }}